#!/usr/bin/env python3
"""Generates fputest.S — exercises the FPU opmodes added to
m68kfpu.c through patches/musashi/0005. Each test loads an int32
into FP0 (FMOVE.L Dn,FP0), runs the op in place, and stores the
rounded int32 result to (A0)+ in chip RAM. FPU opcodes are hand-encoded
as dc.w (Musashi fpgen_rm_reg/fmove_reg_mem field layout), not vasm
mnemonics — coverage of 040 FPU mnemonics varies by assembler.
Run via run.sh, not directly.
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))

TESTS = [
    # (name, d0_input, opmode, expected_int_result)
    ("FSQRT",    4, 0x04, 2),
    ("FETOX",    0, 0x10, 1),
    ("FETOXM1",  0, 0x08, 0),
    ("FLOGN",    1, 0x14, 0),
    ("FLOGNP1",  0, 0x06, 0),
    ("FLOG10",   1, 0x15, 0),
    ("FLOG2",    1, 0x16, 0),
    ("FTWOTOX",  3, 0x11, 8),
    ("FTENTOX",  2, 0x12, 100),
    ("FSIN",     0, 0x0e, 0),
    ("FCOS",     0, 0x1d, 1),
    ("FTAN",     0, 0x0f, 0),
    ("FASIN",    0, 0x0c, 0),
    ("FACOS",    1, 0x1c, 0),
    ("FATAN",    0, 0x0a, 0),
    ("FSINH",    0, 0x02, 0),
    ("FCOSH",    0, 0x19, 1),
    ("FTANH",    0, 0x09, 0),
    ("FATANH",   0, 0x0d, 0),
    ("FGETMAN",  8, 0x1f, 1),
]


def main():
    lines = [
        "; fputest.S — generated by gen_fputest.py.",
        "; Exercises the FPU opmodes added by patches/musashi/0005.",
        "; FPU opcodes are hand-encoded as dc.w (Musashi fpgen_rm_reg/",
        "; fmove_reg_mem field layout) so this does not depend on vasm's",
        "; FPU mnemonic coverage.",
        "        org     $fc0000",
        "        dc.l    $001ff00        ; SSP",
        "        dc.l    START            ; PC",
        "",
        "START:",
        "        ; Drop OVL so Chip RAM answers at low addresses. Until this",
        "        ; runs the ROM overlays them, and the harness --dump that",
        "        ; collects the results would read ROM instead.",
        "        move.b  #$01,$bfe201    ; CIA-A DDRA: PRA bit 0 to output",
        "        move.b  #$00,$bfe001    ; CIA-A PRA:  drive OVL low",
        "",
        "        move.l  #$1000,a0       ; result buffer in chip RAM",
        "",
    ]

    for name, d0val, opmode, expected in TESTS:
        lines += [
            f"        ; {name}({d0val}) -> expect {expected}",
            f"        move.l  #{d0val},d0",
            "        dc.w    $F200,$4000     ; FMOVE.L D0,FP0",
            f"        dc.w    $F200,${opmode:04X}     ; {name} FP0,FP0",
            "        dc.w    $F218,$6000     ; FMOVE.L FP0,(A0)+",
            "",
        ]

    lines += [
        "        ; FSCALE(dst=1.0, scale=3) -> expect 8",
        "        move.l  #1,d0",
        "        dc.w    $F200,$4000     ; FMOVE.L D0,FP0",
        "        move.l  #3,d1",
        "        dc.w    $F201,$4080     ; FMOVE.L D1,FP1",
        "        dc.w    $F200,$0426     ; FSCALE FP1,FP0",
        "        dc.w    $F218,$6000     ; FMOVE.L FP0,(A0)+",
        "",
        "DONE:",
        "        move.l  #$5a5a5a5a,(a0) ; sentinel: marks end of results",
        "        bra.s   DONE",
    ]

    with open(os.path.join(HERE, "fputest.S"), "w") as f:
        f.write("\n".join(lines) + "\n")

    names = [t[0] for t in TESTS] + ["FSCALE"]
    expected = [t[3] for t in TESTS] + [8]
    with open(os.path.join(HERE, "expected.json"), "w") as f:
        json.dump({"names": names, "expected": expected}, f, indent=2)

    print(f"Generated {len(TESTS) + 1} tests")


if __name__ == "__main__":
    main()
