#!/usr/bin/env python3
"""Convert a binary file into a C source file with an embedded byte array.

Usage: rom_to_c.py <input> <output.c> [--symbol <name>]

--symbol NAME   Base name for generated symbols (default: lide_rom).
                Produces:  const unsigned char g_<NAME>_data[];
                           const size_t        g_<NAME>_size;
"""
import sys


def main(bin_path, c_path, symbol='lide_rom'):
    with open(bin_path, 'rb') as f:
        data = f.read()

    data_sym = f'g_{symbol}_data'
    size_sym = f'g_{symbol}_size'

    with open(c_path, 'w') as f:
        f.write('/* Auto-generated by scripts/rom_to_c.py — do not edit */\n')
        f.write('#include <stddef.h>\n\n')
        f.write(f'const unsigned char {data_sym}[] = {{\n')
        for i, b in enumerate(data):
            if i % 16 == 0:
                f.write('    ')
            f.write(f'0x{b:02x},')
            if i % 16 == 15:
                f.write('\n')
            else:
                f.write(' ')
        if len(data) % 16 != 0:
            f.write('\n')
        f.write('};\n\n')
        f.write(f'const size_t {size_sym} = {len(data)}u;\n')

    print(f'Embedded {len(data)} bytes from {bin_path} into {c_path} '
          f'(symbols: {data_sym}, {size_sym})')


if __name__ == '__main__':
    args = sys.argv[1:]
    symbol = 'lide_rom'

    # Parse --symbol
    if '--symbol' in args:
        idx = args.index('--symbol')
        if idx + 1 >= len(args):
            sys.exit('Error: --symbol requires a value')
        symbol = args[idx + 1]
        args = args[:idx] + args[idx + 2:]

    if len(args) != 2:
        sys.exit(f'Usage: {sys.argv[0]} <input> <output.c> [--symbol <name>]')

    main(args[0], args[1], symbol)
